name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Create keystore
        run: |
          keytool -genkey -v -keystore fastcamera.keystore -alias fastcamera -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass android123 -keypass android123 \
            -dname "CN=FastCamera, OU=Dev, O=Volodapatik, L=Kyiv, S=Kyiv, C=UA"

      - name: Build Release APK (signed)
        run: |
          gradle assembleRelease --stacktrace \
            -Pandroid.injected.signing.store.file=$PWD/fastcamera.keystore \
            -Pandroid.injected.signing.store.password=android123 \
            -Pandroid.injected.signing.key.alias=fastcamera \
            -Pandroid.injected.signing.key.password=android123

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: FastCamera-release
          path: app/build/outputs/apk/release/*.apk
          retention-days: 14
          if-no-files-found: error
